#!/bin/bash
 
xsetroot -cursor_name left_ptr
sxhkd &
polybar &
picom --experimental-backends &
feh --bg-scale './wallpapers/Mountain.png'

bspc monitor -d 1 2 3 4 5 

bspc config border_width	2
bspc config window_gap		10
 
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc rule -a Chromium desktop='^2'
bspc rule -a Gimp desktop='^8' state=floating follow=on
